#!/bin/bash

quiet_run() {
	# =============================================================
	# mcecho -e_off=1
	mcdo gamerule sendCommandFeedback false
	# =============================================================
	$1
	$2
	$3
	# =============================================================
	mcdo gamerule sendCommandFeedback true
	# mcecho -e_off=
}


s74
# s66
