#!/bin/bash

set -e

tmp_file="/tmp/reset-mysql-password.sql"
echo -e -n "Enter new root password :"
read new_pass
sudo /etc/init.d/mysql stop
sudo mysqld_safe --skip-grant-tables &
echo -e  "use mysql;" > $tmp_file
echo -e "update user set password=PASSWORD(\"${new_pass}\") where User='root';" >> $tmp_file
echo -e "flush privileges;" >> $tmp_file
echo -e "quit" >> $tmp_file
mysql -u root < $tmp_file

/etc/init.d/mysql stop
rm $tmp_file
/etc/init.d/mysql start

echo -e "Done :)"
