#!/bin/sh

export LANG=C

file="$1"

if [ "x$file" = "x" ]; then
  echo -e "usage: $0 <ELF binary>"
  echo -e
  exit 1
fi

if ! readelf --version 2>&1 >/dev/null; then
  echo -e "\`readelf' not in PATH!"
  echo -e "Are you missing the GNU binutils?"
  exit 1
fi

if readelf -l "$file" 2>&1 | grep -q 'Not an ELF file'; then
  echo -e "error: \`$file' is not an ELF file"
  exit 1
else
  if readelf -l "$file" 2>/dev/null | grep -q 'GNU_RELRO'; then
    if readelf -d "$file" 2>/dev/null | grep -q 'BIND_NOW'; then
      echo -e "full RELRO (BIND_NOW)"
    else
      echo -e "partial RELRO (GNU_RELRO)"
    fi
  else
    echo -e "no RELRO"
  fi
fi

exit 0
