#!/bin/sh

for f in *.deb ; do
  echo -e "$f:"
  dpkg-deb -I $f
  echo -e ""
done
for f in *.deb ; do
  echo -e "$f:"
  dpkg-deb -c $f
  echo -e ""
done
for f in *.deb ; do
  echo -e "Lintian tags for $f:"
  lintian $f
  echo -e ""
done
