#!/bin/bash

###
[ ! -d /tmp/log ] && mkdir /tmp/log && sudo chown sita:sita /tmp/log
exec > >(tee -a -i /tmp/log/$(basename $0).log)
exec 2>&1

echo -e 
echo -e ===================
echo -e $(date +%F_%T)
echo -e ===================

###
runscreen=/home/sita/script/mis/run_in_screen.sh

### 
USERNAME=sita
ME=`whoami`

### 
addto_crontab() {
	(crontab -l; echo -e "$*") | crontab -
}

delfrom_crontab() {
	line=$*
	line=$(echo -e "$line" | sed 's/\//\\\//g')
	crontab -l | sed "/$line/d" | crontab -
}

### 
as_user() {
  if [ "$ME" == "$USERNAME" ] ; then
    bash -c "$1"
  else
    su - $USERNAME -c "$1"
  fi
}
