#!/bin/bash
set -euf -o pipefail

##
# Translate to lower case.
#
# Example:
#
#     $ echo -e "Hello World" | tr-lower
#     hello world
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

tr '[:upper:]' '[:lower:]'
