#!/bin/bash

BASENAME=$(basename $0)

[ -d /mnt/$BASENAME ] || sudo mkdir /mnt/$BASENAME

sudo umount /mnt/$BASENAME >/dev/null
sudo mount -t nfs -o nosuid,noexec,nodev,bg,soft $BASENAME:/export /mnt/$BASENAME

echo -e alias $BASENAME="\"cd /mnt/$BASENAME\""
