#!/bin/bash

s75=75-UHC2

# s75() {
	# oldmcvar=$mcver
	# export mcver=$s75 
	
	# mcpath=/mnt/runtimes/$mcver
	# [ ! -d "$mcpath" ] && { echo -e -e "${YELLOW}$mcpath not installed${NC}"; mcver=$oldmcvar; }
	# [   -d "$mcpath" ] && { echo -e mcver=$mcver; cd $mcpath; }
# }

s75() {
	chmc $s75
}

alias v11u=s75
alias 75=s75
alias uhc2=s75
