#!/bin/bash

s78=78-ParkourSpiral2

s78() {
	oldmcvar=$mcver
	export mcver=$s78 
	
	mcpath=/mnt/runtimes/$mcver
	[ ! -d "$mcpath" ] && { echo -e -e "${YELLOW}$mcpath not installed${NC}"; mcver=$oldmcvar; }
	[   -d "$mcpath" ] && { echo -e mcver=$mcver; cd $mcpath; }
	
	alias  s1='export pos="-10 205 15"    && echo -e pos=繞過關卡的蟲'
}

s78() {
	chmc $s78
	
	alias  s1='export pos="-10 205 15"    && echo -e pos=繞過關卡的蟲'
}

alias 78=s78
alias pk2=s78
