#!/bin/bash

PK8=$1
X509PEM=$2
ALIAS=$3
STORENAME=$4
PWREQ=$5

CRYPT=

if [ -z "$PK8" ]; then
    echo -e "Please provide the following:"
    echo -e "      .pk8,"
    echo -e "      .x509.pem,"
    echo -e "      desired alias,"
    echo -e "      desired keystore name,"
    echo -e "      and if pw should be required (optional)"
    exit 1
fi

if [ ! -z "$PWREQ" ]; then
    CRYPT="-nocrypt"
fi

openssl pkcs8 -inform DER $CRYPT -in $PK8 -out key.pem

if [ ! -z $CRYPT ]; then
    STOREPASS=android
else
    echo -e "Enter keystore pass:"
    read STOREPASS
fi
openssl pkcs12 -export -in $X509PEM -inkey key.pem -out platform.p12 -password pass:$STOREPASS -name $ALIAS

if [ ! -z $CRPYT ]; then
    KEYPASS=password
else
    echo -e "Enter key pass:"
    read KEYPASS
fi
keytool -importkeystore -deststorepass $KEYPASS -destkeystore $STORENAME -srckeystore platform.p12 -srcstoretype PKCS12 -srcstorepass $STOREPASS

