#!/bin/bash

. /home/sita/script/include/console.color
. /home/sita/script/include/gcloud_helper

###
dnsupdate=/home/sita/script/mis/gcloud.dns.update.sh

###
dns_account=chsliu@gmail.com
default_account=$(get_account)

### 
addto_crontab() {
	(crontab -l; echo -e "$*") | crontab -
}

delfrom_crontab() {
	line=$*
	line=$(echo -e "$line" | sed 's/\//\\\//g')
	crontab -l | sed "/$line/d" | crontab -
}

###
HOST=$(basename $0)

start() {
    set_account $dns_account
    
    # DNS transaction start
    echo -e -e ${YELLOW}=== Starting DNS Changes: ${GREEN}$HOST.creeper.tw ${NC}
    $dnsupdate start creeper-196707 creeper-tw

    if [ $(date +%H) == '06' ]; then
        # On 6am
        # del A r53.creeper.tw 3hour 1min
        echo -e -e ${GREEN}== Deleting ${YELLOW}r53.creeper.tw 1min IN A ... ${NC}
        $dnsupdate del creeper-196707 creeper-tw r53 creeper.tw 3hour 1min A
    fi

    if [ $(date +%w) == 6 ]; then
        # On Saturday
        # A tp1.creeper.tw 1min
        echo -e -e ${GREEN}== Updating ${YELLOW}$HOST.creeper.tw ${GREEN}3hour to ${YELLOW}1min IN A ... ${NC}
        $dnsupdate A creeper-tw $HOST creeper.tw 3hour 1min
        
        # A gem.creeper.tw 1min
        echo -e -e ${GREEN}== Updating ${YELLOW}gem.creeper.tw ${GREEN}3hour to ${YELLOW}1min IN A ... ${NC}
        $dnsupdate A creeper-tw gem creeper.tw 3hour 1min
        
        # CNAME mc.creeper.tw = tp1.creeper.tw 1min
        echo -e -e ${GREEN}== Updating ${YELLOW}mc.creeper.tw ${GREEN}3hour to ${YELLOW}1min IN CNAME $HOST.creeper.tw ${NC}
        $dnsupdate CNAME creeper-tw mc creeper.tw $HOST.creeper.tw. 3hour 1min
        
        # A wiki.creeper.tw 1min
        echo -e -e ${GREEN}== Updating ${YELLOW}wiki.creeper.tw ${GREEN}3hour to ${YELLOW}1min IN A ... ${NC}
        $dnsupdate A creeper-tw wiki creeper.tw 3hour 1min

        # append A r53.creeper.tw 1min
        # echo -e -e ${GREEN}=== Appending A r53.creeper.tw 1min ${NC}
        # $dnsupdate append creeper-196707 creeper-tw r53 creeper.tw 3hour 1min A
    else
        # Not Saturday
        # A tp1.creeper.tw 3hour
        echo -e -e ${GREEN}== Updating ${YELLOW}$HOST.creeper.tw ${GREEN}1min to ${YELLOW}3hour IN A ... ${NC}
        $dnsupdate A creeper-tw $HOST creeper.tw 1min 3hour
        
        # A gem.creeper.tw 3hour
        echo -e -e ${GREEN}== Updating ${YELLOW}gem.creeper.tw ${GREEN}1min to ${YELLOW}3hour IN A ... ${NC}
        $dnsupdate A creeper-tw gem creeper.tw 1min 3hour
        
        # CNAME mc.creeper.tw = tp1.creeper.tw 3hour
        echo -e -e ${GREEN}== Updating ${YELLOW}mc.creeper.tw ${GREEN}1min to ${YELLOW}3hour IN CNAME $HOST.creeper.tw ${NC}
        $dnsupdate CNAME creeper-tw mc creeper.tw $HOST.creeper.tw. 1min 3hour
        
        # A wiki.creeper.tw 1min
        echo -e -e ${GREEN}== Updating ${YELLOW}wiki.creeper.tw ${GREEN}1min to ${YELLOW}3hour IN A ... ${NC}
        $dnsupdate A creeper-tw wiki creeper.tw 1min 3hour     
        
        # A r53.creeper.tw 3hour
        # echo -e -e ${GREEN}=== Appending A r53.creeper.tw 3hour ${NC}
        # $dnsupdate A creeper-tw r53 creeper.tw 1min 3hour
    fi

    # DNS transaction commit
    echo -e -e ${YELLOW}=== Commiting DNS Changes: ${GREEN}$HOST.creeper.tw ${NC}
    $dnsupdate commit creeper-196707 creeper-tw
    
    set_account $default_account
}

start2() {
    set_account $dns_account
    
    # DNS transaction start
    echo -e -e ${YELLOW}=== Starting DNS Changes: ${GREEN}home.changen.com.tw ${NC}
    $dnsupdate start creeper-196707 changen-com-tw

    if [ $(date +%w) == 6 ]; then
        # On Saturday
        # A home.changen.com.tw 1min
        echo -e -e ${GREEN}== Updating ${YELLOW}home.changen.com.tw ${GREEN}3hour to ${YELLOW}1min IN A ...${NC}
        $dnsupdate A changen-com-tw home changen.com.tw 3hour 1min
    else
        # Not Saturday
        # A home.changen.com.tw 3hour
        echo -e -e ${GREEN}= Updating ${YELLOW}home.changen.com.tw ${GREEN}1min to ${YELLOW}3hour IN A ... ${NC}
        $dnsupdate A changen-com-tw home changen.com.tw 1min 3hour
    fi

    # DNS transaction commit
    echo -e -e ${YELLOW}=== Commiting DNS Changes: ${GREEN}home.changen.com.tw ${NC}
    $dnsupdate commit creeper-196707 changen-com-tw
    
    set_account $default_account
}

stop() {
    echo -e Stopping $(basename $0) ...
}

###
case "$1" in
  install)
	addto_crontab "#gcloud DNS update $(basename $0)"
    addto_crontab "5 6 * * * /bin/bash $(readlink -e $0)"
    exit
    ;;
  remove)
    delfrom_crontab "$(basename $0)"
    exit
    ;;
  start)
    start
    start2
    exit
    ;;
  stop)
    stop
    exit
    ;;
  *)
    start
    start2
esac
