#!/bin/bash

. /home/sita/script/include/console.color
. /home/sita/script/include/gcloud_helper

###
dnsupdate=/home/sita/script/mis/gcloud.dns.update.sh

###
dns_account=chsliu@gmail.com
default_account=$(get_account)

### 
addto_crontab() {
	(crontab -l; echo -e "$*") | crontab -
}

delfrom_crontab() {
	line=$*
	line=$(echo -e "$line" | sed 's/\//\\\//g')
	crontab -l | sed "/$line/d" | crontab -
}

###
HOST=$(basename $0)
default_HOST=tp1
# HOST=$(hostname)
bc_single_host="bungeecord-tw2"

start() {
    set_account $dns_account
    
    if [ $(hostname) == $bc_single_host ]; then
        # DNS transaction start
        echo -e -e ${YELLOW}=== Starting DNS Changes: ${GREEN}$(basename $0).creeper.tw ${NC}
        $dnsupdate start creeper-196707 creeper-tw
    fi

    if [ $(date +%w) == 6 ]; then
        # On Saturday
        if [ $(hostname) == $bc_single_host ]; then
            # hostname is tw2
            
            # A tw2.creeper.tw 1min
            echo -e -e ${GREEN}== Updating ${YELLOW}$HOST.creeper.tw 1min IN A ... ${NC}
            $dnsupdate A creeper-tw $HOST creeper.tw 3hour 1min
            
            # CNAME mc.creeper.tw = tw2.creeper.tw 1min
            echo -e -e ${GREEN}== Updating ${YELLOW}mc.creeper.tw ${GREEN}3hour to ${YELLOW}1min IN CNAME $HOST.creeper.tw ${NC}
            $dnsupdate CNAME creeper-tw mc creeper.tw $HOST.creeper.tw. 3hour 1min
        # else
            # hostname not tw2
            
            # CNAME mc.creeper.tw = lb.creeper.tw 1min
            # echo -e -e ${GREEN}=== Updating CNAME ${YELLOW}mc.creeper.tw = lb.creeper.tw ${GREEN}3hour to ${YELLOW}1min ${NC}
            # $dnsupdate CNAME creeper-tw mc creeper.tw lb.creeper.tw. 3hour 1min
        fi

        # append A r53.creeper.tw 1min
        # echo -e -e ${GREEN}=== Appending A ${YELLOW}r53.creeper.tw 1min ${NC}
        # $dnsupdate append creeper-196707 creeper-tw r53 creeper.tw 3hour 1min A
    else
        # Not Saturday
        if [ $(hostname) == $bc_single_host ]; then
            # hostname is tw2
            # A tw2.creeper.tw 3hour
            echo -e -e ${GREEN}== Updating ${YELLOW}$HOST.creeper.tw 3hour IN A ... ${NC}
            $dnsupdate A creeper-tw $HOST creeper.tw 1min 3hour
            
            # CNAME mc.creeper.tw = tw2.creeper.tw 3hour
            echo -e -e ${GREEN}== Updating ${YELLOW}mc.creeper.tw ${GREEN}1min to ${YELLOW}3hour IN CNAME $HOST.creeper.tw ${NC}
            $dnsupdate CNAME creeper-tw mc creeper.tw $HOST.creeper.tw. 1min 3hour
        # else
            # hostname not tw2
            
            # CNAME mc.creeper.tw = lb.creeper.tw 3hour
            # echo -e -e ${GREEN}=== Updating CNAME ${YELLOW}mc.creeper.tw = lb.creeper.tw ${GREEN}1min to ${YELLOW}3hour ${NC}
            # $dnsupdate CNAME creeper-tw mc creeper.tw lb.creeper.tw. 1min 3hour
        fi
        
        # append A r53.creeper.tw 3hour
        # echo -e -e ${GREEN}=== Appending A ${YELLOW}r53.creeper.tw 3hour ${NC}
        # $dnsupdate append creeper-196707 creeper-tw r53 creeper.tw 1min 3hour A
    fi

    if [ $(hostname) == $bc_single_host ]; then
        # DNS transaction commit
        echo -e -e ${YELLOW}=== Commiting DNS Changes: ${GREEN}$(basename $0).creeper.tw ${NC}
        $dnsupdate commit creeper-196707 creeper-tw
    fi
    
    set_account $default_account
}

stop() {
    set_account $dns_account
    
    if [ $(hostname) == $bc_single_host ]; then
        # DNS transaction start
        echo -e -e ${YELLOW}=== Starting DNS Changes: ${GREEN}$(basename $0).creeper.tw ${NC}
        $dnsupdate start creeper-196707 creeper-tw
    fi
    
    # if [ $(date +%w) == 6 ]; then
        # On Saturday

        # if [ $(hostname) == $bc_single_host ]; then
            # hostname is tw2
            # del A tw2.creeper.tw 3hour 1min
            # echo -e -e ${GREEN}=== Deleting A ${YELLOW}$HOST.creeper.tw ${NC}
            # $dnsupdate del creeper-196707 creeper-tw $HOST creeper.tw 3hour 1min A
        # fi
        
        # remove A r53.creeper.tw 1min
        # echo -e -e ${GREEN}=== Removing A ${YELLOW}r53.creeper.tw 1min ${NC}
        # $dnsupdate remove creeper-196707 creeper-tw r53 creeper.tw 3hour 1min A
    # else
        # Not Saturday

        # if [ $(hostname) == $bc_single_host ]; then
            # hostname is tw2
            # del A tw2.creeper.tw 3hour 1min
            # echo -e -e ${GREEN}=== Deleting A ${YELLOW}$HOST.creeper.tw ${NC}
            # $dnsupdate del creeper-196707 creeper-tw $HOST creeper.tw 3hour 1min A
        # fi
        
        # remove A r53.creeper.tw 3hour
        # echo -e -e ${GREEN}=== Removing A ${YELLOW}r53.creeper.tw 3hour ${NC}
        # $dnsupdate remove creeper-196707 creeper-tw r53 creeper.tw 1min 3hour A
    # fi

    if [ $(hostname) == $bc_single_host ]; then
        # hostname is tw2
        # del A tw2.creeper.tw 3hour 1min
        echo -e -e ${GREEN}== Deleting ${YELLOW}$HOST.creeper.tw 1min IN A ... ${NC}
        $dnsupdate del creeper-196707 creeper-tw $HOST creeper.tw 3hour 1min A

        # CNAME mc.creeper.tw = tw2.creeper.tw 3hour
        echo -e -e ${GREEN}== Updating ${YELLOW}mc.creeper.tw ${GREEN}1min to ${YELLOW}3hour IN CNAME $default_HOST.creeper.tw ${NC}
        $dnsupdate CNAME creeper-tw mc creeper.tw $default_HOST.creeper.tw. 1min 3hour
    fi

    if [ $(hostname) == $bc_single_host ]; then
        # DNS transaction commit
        echo -e -e ${YELLOW}=== Commiting DNS Changes: ${GREEN}$(basename $0).creeper.tw ${NC}
        $dnsupdate commit creeper-196707 creeper-tw
    fi
    
    set_account $default_account
}

###
case "$1" in
  install)
	addto_crontab "#gcloud DNS update $(basename $0)"
    addto_crontab "10 6 * * * /bin/bash $(readlink -e $0)"
    exit
    ;;
  remove)
    delfrom_crontab "$(basename $0)"
    exit
    ;;
  start)
    start
    exit
    ;;
  stop)
    stop
    exit
    ;;
  *)
    start
esac
