#!/bin/bash

. /home/sita/script/include/console.color
. /home/sita/script/include/gcloud_helper

###
dnsupdate=/home/sita/script/mis/gcloud.dns.update.sh

###
dns_account=chsliu@gmail.com
default_account=$(get_account)

### 
addto_crontab() {
	(crontab -l; echo "$*") | crontab -
}

delfrom_crontab() {
	line=$*
	line=$(echo "$line" | sed 's/\//\\\//g')
	crontab -l | sed "/$line/d" | crontab -
}

###
HOST=$(basename $0)

start() {
    set_account $dns_account
    
    # DNS transaction start
    echo -e ${YELLOW}=== Starting DNS Changes: ${GREEN}$HOST.creeper.tw ${NC}
    $dnsupdate start creeper-196707 creeper-tw

    # A www.creeper.tw 1hour
    echo -e ${GREEN}== Updating ${YELLOW}$HOST.creeper.tw 3hour IN A ... ${NC}
    $dnsupdate A creeper-tw $HOST creeper.tw 3hour 3hour

    # A creeper.tw 1hour
    echo -e ${GREEN}== Updating ${YELLOW}creeper.tw 3hour IN A ... ${NC}
    $dnsupdate A creeper-tw @ creeper.tw 3hour 3hour

    # DNS transaction commit
    echo -e ${YELLOW}=== Commiting DNS Changes: ${GREEN}$HOST.creeper.tw ${NC}
    $dnsupdate commit creeper-196707 creeper-tw
    
    set_account $default_account
}

stop() {
    echo Stopping $(basename $0) ...
}

###
case "$1" in
  install)
	addto_crontab "#gcloud DNS update $(basename $0)"
    addto_crontab "10 6 * * * /bin/bash $(readlink -e $0)"
    exit
    ;;
  remove)
    delfrom_crontab "$(basename $0)"
    exit
    ;;
  start)
    start
    exit
    ;;
  stop)
    stop
    exit
    ;;
  *)
    start
esac
