#!/bin/bash

rpool=tank

if [ ! -d "/$rpool" ]; then
        echo zpool $rpool not created, aborting
        exit
fi

zfs_create() {
        if [ -d "/$1" ]; then return; fi

        echo Creating $*
        sudo zfs create -o xattr=sa -o compression=lz4 $*
}

zfs_create $rpool/USBROOT
sudo rsync -avx --delete / /$rpool/USBROOT/
sudo rsync -avx --delete /etc/pve/ /$rpool/USBROOT/etc/pve/
